name: Tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        stability: [ prefer-stable ]
        include:
          - dependency-versions: "lowest"
          - symfony-require: "6.0.*"
            php-version: "8.0"
          - symfony-require: "6.1.*"
            php-version: "8.1"
          - symfony-require: "6.2.*"
            php-version: "8.1"
          - symfony-require: "6.3.*"
            php-version: "8.1"

    name: PHP ${{ matrix.php-version }} - Symfony ${{ symfony-require }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: xdebug
      - name: "Install symfony/flex"
        run: "composer require --no-progress --no-scripts --no-plugins symfony/flex"
      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependency-versions }}"
          max_attempts: 5
          timeout_minutes: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            composer global require php-coveralls/php-coveralls
            php-coveralls --coverage_clover=build/logs/clover.xml -v